---
title: "Quiz 1"
author: "Amy Su Jiang"
output: html_document
---


Introduction

This first quiz will check your ability to execute basic operations on objects in R and to understand some basic concepts. For questions 11–20 you will need to load a dataset into R and do some basic manipulations in order to answer the questions on the quiz.

You may want to print a copy of the quiz questions to look at as you work on the assignment. It is recommended that you save your answers as you go in the event that a technical problem should occur with your network connection or computer. Ultimately, you must submit the quiz online to get credit!
Data

The zip file containing the data for questions 11–20 in this Quiz can be downloaded here:

    [Week 1 Quiz Data](https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fquiz1_data.zip)

For this assignment you will need to unzip this file in your working directory.
In accordance with the Coursera Honor Code, I (amy jiang) certify that the answers here are my own work.

### Question 1

The R language is a dialect of which of the following programming languages?

    S
    Lisp
    C
    Fortran

### Question 2

The definition of free software consists of four freedoms (freedoms 0 through 3). Which of the following is NOT one of the freedoms that are part of the definition?

    The freedom to redistribute copies so you can help your neighbor.
    The freedom to sell the software for any price.
    The freedom to run the program, for any purpose.
    The freedom to improve the program, and release your improvements to the public, so that the whole community benefits.

### Question 3

In R the following are all atomic data types EXCEPT

    integer
    complex
    matrix
    character

### Question 4

If I execute the expression x <- 4 in R, what is the class of the object `x' as determined by the `class()' function?

    numeric
    vector
    real
    matrix

### Question 5

What is the class of the object defined by x <- c(4, TRUE)?

    list
    numeric
    character
    matrix

### Question 6

If I have two vectors x <- c(1,3, 5) and y <- c(3, 2, 10), what is produced by the expression cbind(x, y)?

    a 3 by 2 numeric matrix
    a 3 by 3 matrix
    a 2 by 2 matrix
    a 2 by 3 matrix

### Question 7

A key property of vectors in R is that

    elements of a vector can be of different classes
    the length of a vector must be less than 32,768
    elements of a vector can only be character or numeric
    elements of a vector all must be of the same class

### Question 8

Suppose I have a list defined as x <- list(2, "a", "b", TRUE). What does x[[2]] give me?

    a character vector with the elements "a" and "b".
    a list containing a character vector with the elements "a" and "b".
    a character vector of length 1.
    a list containing character vector with the letter "a".

### Question 9

Suppose I have a vector x <- 1:4 and y <- 2:3. What is produced by the expression x + y?

    a numeric vector with the values 3, 5, 3, 4.
    an integer vector with the values 3, 5, 3, 4.
    a warning
    an integer vector with the values 3, 5, 5, 7.

### Question 10

Suppose I have a vector x <- c(17, 14, 4, 5, 13, 12, 10) and I want to set all elements of this vector that are greater than 10 to be equal to 4. What R code achieves this?

    x[x == 4] > 10
    x[x > 10] <- 4
    x[x > 4] <- 10
    x[x >= 10] <- 4

### Question 11

In the dataset provided for this Quiz, what are the column names of the dataset?

    Ozone, Solar.R, Wind, Temp, Month, Day
    1, 2, 3, 4, 5, 6
    Month, Day, Temp, Wind
    Ozone, Solar.R, Wind

### Question 12

Extract the first 2 rows of the data frame and print them to the console. What does the output look like?

      Ozone Solar.R Wind Temp Month Day
    1     9      24 10.9   71     9  14
    2    18     131  8.0   76     9  29
    
      Ozone Solar.R Wind Temp Month Day
    1    41     190  7.4   67     5   1
    2    36     118  8.0   72     5   2
    
      Ozone Solar.R Wind Temp Month Day
    1    18     224 13.8   67     9  17
    2    NA     258  9.7   81     7  22
    
      Ozone Solar.R Wind Temp Month Day
    1     7      NA  6.9   74     5  11
    2    35     274 10.3   82     7  17

### Question 13

How many observations (i.e. rows) are in this data frame?

    153
    45
    129
    160

### Question 14

Extract the last 2 rows of the data frame and print them to the console. What does the output look like?

        Ozone Solar.R Wind Temp Month Day
    152    11      44  9.7   62     5  20
    153   108     223  8.0   85     7  25
    
        Ozone Solar.R Wind Temp Month Day
    152    18     131  8.0   76     9  29
    153    20     223 11.5   68     9  30
    
        Ozone Solar.R Wind Temp Month Day
    152    31     244 10.9   78     8  19
    153    29     127  9.7   82     6   7
    
        Ozone Solar.R Wind Temp Month Day
    152    34     307 12.0   66     5  17
    153    13      27 10.3   76     9  18

### Question 15

What is the value of Ozone in the 47th row?

    21
    63
    34
    18

### Question 16

How many missing values are in the Ozone column of this data frame?

    9
    37
    78
    43

### Question 17

What is the mean of the Ozone column in this dataset? Exclude missing values (coded as NA) from this calculation.

    42.1
    18.0
    53.2
    31.5

### Question 18

Extract the subset of rows of the data frame where Ozone values are above 31 and Temp values are above 90. What is the mean of Solar.R in this subset?

    334.0
    185.9
    205.0
    212.8

### Question 19

What is the mean of "Temp" when "Month" is equal to 6?

    85.6
    90.2
    79.1
    75.3

### Question 20

What was the maximum ozone value in the month of May (i.e. Month = 5)?

    100
    115
    18
    97
